export const FEATURE_NAME_METADATA = 'OPTIMUS_FEATURE_NAME_METADATA';
export const ACTION_NAME_METADATA = 'OPTIMUS_ACTION_NAME_METADATA';
export const OVERRIDE_METHOD_METADATA = 'OPTIMUS_OVERRIDE_METHOD_METADATA';
export const PARSED_BODY_METADATA = 'OPTIMUS_PARSED_BODY_METADATA';
export const PARSED_CRUD_REQUEST_KEY = 'OPTIMUS_PARSED_CRUD_REQUEST_KEY';
export const CRUD_OPTIONS_METADATA = 'OPTIMUS_CRUD_OPTIONS_METADATA';
export const CRUD_AUTH_OPTIONS_METADATA = 'OPTIMUS_CRUD_AUTH_OPTIONS_METADATA';
